### ISSUE TITLE
php artisan migrate Error

### ISSUE THREAD

**Issue by cloudi32003** [kmanjari/hrms#35]
Hi Kmanjari,

I have this error when running php artisan migrate. Please advise and help on this issue.

C:\xampp\htdocs\hrms-master>php artisan migrate
Migration table created successfully.
  [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1059 Identifier name 'a
         schema::drop('assign_assets');
  ssign_assets_user_id_foreign' is too long (SQL: alter table `a        Schem
  a::drop('assign_assets');
  ssign_assets` add constraint `a        schema::drop('assign_assets');
  ssign_assets_user_id_foreign` foreign key (`user_id`) references `users` (`
  id`) on delete cascade)

  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1059 Identifier name 'a
         schema::drop('assign_assets');
  ssign_assets_user_id_foreign' is too long

**Comment by khanof89** [comment]
There was some invalid code in table migration which is fixed now, please open issues if you find any further

**Comment by cloudi32003** [comment]
Hi Shahrukh,

Yes I had clone the latest code and still having error when running php
artisan migrate.

May I know why i'm still not able to login using the dataseeder email and
password to login.

Best Regards,
Johnny Lee
